version: '3'
services:
  service1-1:
    build: ./service1
    depends_on:
      - service2

  service1-2:
    build: ./service1
    depends_on:
      - service2

  service1-3:
    build: ./service1
    depends_on:
      - service2

  service2:
    build: ./service2

  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - shutdown_service
      - auth_service

  auth_service:
    build: ./auth_service

  shutdown_service:
    build: ./shutdown_service
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
